# Generated by Django 3.0.4 on 2020-07-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='idproducton',
            field=models.IntegerField(default=0),
        ),
    ]
